#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install pretty-quick --staged --pattern '!test/tests/lint/**'
# npx --no-install pretty-quick --staged --pattern '!test/tests/lint/**' && npm run lint && npm run deduplicate:check && npx --no-install doctoc README.md
