name: Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-dedupe:
    runs-on: ubuntu-latest

    name: Lint & Deduplicate deps on node 10.x and ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint codebase
        run: npm run lint:post-build

      # Can't use this yet until npm supports overrides :/
      # - name: Deduplicate dependencies
      #   run: npm run deduplicate:check

  test:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test package
        run: npm run test:post-build
